---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myZone:
    Type: String
    Description: Enter the Route53 Hosted Zone ID
  myCustomDomain:
    Type: String
    Default: example.com
    Description: Enter the custom root domain name
Resources:
  webBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
  BucketPolicyForOac:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: webBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${webBucket}/*
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            StringEquals:
              AWS:SourceArn:
                Fn::Sub: arn:aws:cloudfront::${AWS::AccountId}:distribution/${cloudfrontDistribution}
  originAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name:
          Ref: AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - Ref: myCustomDomain
        - Fn::Sub: www.${myCustomDomain}
        Origins:
        - DomainName:
            Fn::GetAtt:
            - webBucket
            - DomainName
          Id: myWebsite
          S3OriginConfig: {}
          OriginAccessControlId:
            Fn::GetAtt:
            - originAccessControl
            - Id
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: myWebsite
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: 'true'
        ViewerCertificate:
          AcmCertificateArn:
            Ref: myCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
  myCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        Fn::Sub: "*.${myCustomDomain}"
      DomainValidationOptions:
      - DomainName:
          Ref: myCustomDomain
        HostedZoneId:
          Ref: myZone
      SubjectAlternativeNames:
      - Ref: myCustomDomain
      ValidationMethod: DNS
  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: myZone
      RecordSets:
      - Name:
          Ref: myCustomDomain
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
            - cloudfrontDistribution
            - DomainName
      - Name:
          Ref: myCustomDomain
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
            - cloudfrontDistribution
            - DomainName
      - Name:
          Fn::Sub: www.${myCustomDomain}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
            - cloudfrontDistribution
            - DomainName
      - Name:
          Fn::Sub: www.${myCustomDomain}
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
            - cloudfrontDistribution
            - DomainName
Outputs:
  CDNURL:
    Description: URL for secure access to the website
    Value:
      Fn::GetAtt:
      - cloudfrontDistribution
      - DomainName