---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  webBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: 'true'
        BlockPublicPolicy: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
  BucketPolicyForOac:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: webBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${webBucket}/*
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            StringEquals:
              AWS:SourceArn:
                Fn::Sub: arn:aws:cloudfront::${AWS::AccountId}:distribution/${cloudfrontDistribution}
  originAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name:
          Ref: AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName:
            Fn::GetAtt:
            - webBucket
            - DomainName
          Id: myWebsite
          S3OriginConfig: {}
          OriginAccessControlId:
            Fn::GetAtt:
            - originAccessControl
            - Id
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: myWebsite
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: 'true'
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
Outputs:
  CDNURL:
    Description: URL for secure access to the website
    Value:
      Fn::GetAtt:
      - cloudfrontDistribution
      - DomainName